name: Publish npm Packages

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: '22'
          cache: 'yarn'
          registry-url: https://registry.npmjs.org
          scope: '@graph-render'

      - name: Install dependencies
        run: HUSKY=0 yarn install --frozen-lockfile

      - name: Build all packages
        run: yarn build

      - name: Publish packages
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: node scripts/publish-npm.mjs
